Heart disease dataset

In [78]:
import pandas as pd
import numpy as np

In [79]:
data=pd.read_csv(r"C:\Users\vigne\Downloads\Heart_Disease_Prediction.csv")
data

Age  Sex  Chest pain type   BP  Cholesterol  FBS over 120  EKG results  \
0     70    1                4  130          322             0            2   
1     67    0                3  115          564             0            2   
2     57    1                2  124          261             0            0   
3     64    1                4  128          263             0            0   
4     74    0                2  120          269             0            2   
..   ...  ...              ...  ...          ...           ...          ...   
265   52    1                3  172          199             1            0   
266   44    1                2  120          263             0            0   
267   56    0                2  140          294             0            2   
268   57    1                4  140          192             0            0   
269   67    1                4  160          286             0            2   

     Max HR  Exercise angina  ST depression  Slope of ST  \
0       109                0            2.4            2   
1       160                0            1.6            2   
2       141                0            0.3            1   
3       105                1            0.2            2   
4       121                1            0.2            1   
..      ...              ...            ...          ...   
265     162                0            0.5            1   
266     173                0            0.0            1   
267     153                0            1.3            2   
268     148                0            0.4            2   
269     108                1            1.5            2   

     Number of vessels fluro  Thallium  Heart Disease  
0                          3         3              1  
1                          0         7              0  
2                          0         7              1  
3                          1         7              0  
4                          1         3              0  
..                       ...       ...            ...  
265                        0         7              0  
266                        0         7              0  
267                        0         3              0  
268                        0         6              0  
269                        3         3              1  

[270 rows x 14 columns]

In [80]:
data.shape

(270, 14)

In [81]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 270 entries, 0 to 269
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   Age                      270 non-null    int64  
 1   Sex                      270 non-null    int64  
 2   Chest pain type          270 non-null    int64  
 3   BP                       270 non-null    int64  
 4   Cholesterol              270 non-null    int64  
 5   FBS over 120             270 non-null    int64  
 6   EKG results              270 non-null    int64  
 7   Max HR                   270 non-null    int64  
 8   Exercise angina          270 non-null    int64  
 9   ST depression            270 non-null    float64
 10  Slope of ST              270 non-null    int64  
 11  Number of vessels fluro  270 non-null    int64  
 12  Thallium                 270 non-null    int64  
 13  Heart Disease            270 non-null    int64  
dtypes: float64(1), int64(13)
m

In [82]:
data.isnull().sum()

Age                        0
Sex                        0
Chest pain type            0
BP                         0
Cholesterol                0
FBS over 120               0
EKG results                0
Max HR                     0
Exercise angina            0
ST depression              0
Slope of ST                0
Number of vessels fluro    0
Thallium                   0
Heart Disease              0
dtype: int64

In [83]:
x=data.drop(columns='Heart Disease')
y=data['Heart Disease']

In [84]:
x.shape

(270, 13)

In [85]:
y.shape

(270,)

Naive bayes

In [86]:
from sklearn.model_selection import train_test_split 
from sklearn.naive_bayes import GaussianNB

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=1)
Gmodel=GaussianNB() 

print('training input sample',x_train.shape)
print('training output label',y_train.shape)

print('testing input sample',x_test.shape)
print('testing output label',y_test.shape)

training input sample (216, 13)
training output label (216,)
testing input sample (54, 13)
testing output label (54,)


In [87]:
Gmodel.fit(x_train,y_train) # implementing Gaussian module to find the pattern

train_Gpred=Gmodel.predict(x_train) 

test_Gpred=Gmodel.predict(x_test) 

In [88]:
test_Gpred

array([0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 0], dtype=int64)

In [89]:
train_Gpred

array([0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0], dtype=int64)

In [90]:
train_acc_gau=np.mean(train_Gpred==y_train)

test_acc_gau=np.mean(test_Gpred==y_test)

print('gaussian naive bayes - training accuracy:',train_acc_gau*100,'%')
print('gaussian nb - testing time accuracy:',test_acc_gau*100,'%')


gaussian naive bayes - training accuracy: 86.11111111111111 %
gaussian nb - testing time accuracy: 87.03703703703704 %


Gaussian performs better than all algorithm

In [91]:
from sklearn.naive_bayes import MultinomialNB
Mmodel=MultinomialNB()  # multinomial NB implementing
Mmodel.fit(x_train,y_train)

train_Mpred=Mmodel.predict(x_train)
test_Mpred=Mmodel.predict(x_test)


In [92]:
train_acc_multi=np.mean(train_Mpred==y_train)
test_acc_multi=np.mean(test_Mpred==y_test)
print('multinomial naive bayes - training accuracy:',train_acc_multi*100,'%')
print('multinomial nb - testing time accuracy:',test_acc_multi*100,'%')

multinomial naive bayes - training accuracy: 76.38888888888889 %
multinomial nb - testing time accuracy: 81.48148148148148 %


Logistic Regression

In [93]:
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler

In [94]:
scr = StandardScaler()
sx = scr.fit_transform(x)
sx

array([[ 1.71209356,  0.6894997 ,  0.87092765, ...,  0.67641928,
         2.47268219, -0.87570581],
       [ 1.38213977, -1.45032695, -0.18355874, ...,  0.67641928,
        -0.71153494,  1.18927733],
       [ 0.2822938 ,  0.6894997 , -1.23804513, ..., -0.95423434,
        -0.71153494,  1.18927733],
       ...,
       [ 0.1723092 , -1.45032695, -1.23804513, ...,  0.67641928,
        -0.71153494, -0.87570581],
       [ 0.2822938 ,  0.6894997 ,  0.87092765, ...,  0.67641928,
        -0.71153494,  0.67303154],
       [ 1.38213977,  0.6894997 ,  0.87092765, ...,  0.67641928,
         2.47268219, -0.87570581]])

In [95]:
log_reg = LogisticRegression(random_state=1)
model = log_reg.fit(sx,y)

In [96]:
model.score(sx,y)

0.8518518518518519

In [97]:
newdata = [[70,0,4,200,222,1,2,100,1,1.2,2,0,7]]
model.predict(newdata)

array([1], dtype=int64)

In [98]:
model.predict_proba(newdata)*100

array([[  0., 100.]])

Random Forest 

In [99]:
from sklearn.preprocessing import StandardScaler
ss=StandardScaler()
x_train=ss.fit_transform(x_train) # xtrain = training input samples
x_test=ss.transform(x_test) # xtest - testing input samples

In [100]:
x_train


array([[ 1.14112826, -1.35724179, -0.2235323 , ..., -0.92179769,
        -0.73307794, -0.87385539],
       [ 0.69721344,  0.7367884 , -0.2235323 , ...,  0.65842692,
        -0.73307794, -0.87385539],
       [ 1.03014955,  0.7367884 , -0.2235323 , ..., -0.92179769,
        -0.73307794, -0.87385539],
       ...,
       [ 1.69602178,  0.7367884 , -1.29648734, ..., -0.92179769,
        -0.73307794, -0.87385539],
       [ 0.80819214, -1.35724179,  0.84942274, ...,  2.23865153,
         2.43381876,  1.17780509],
       [ 0.47525603,  0.7367884 , -2.36944237, ..., -0.92179769,
        -0.73307794, -0.87385539]])

In [101]:
x_test

array([[-1.18942454e+00,  7.36788398e-01, -2.23532299e-01,
         4.37838874e-01, -3.15255907e-01, -4.32218911e-01,
         9.70352254e-01,  1.31477694e+00, -6.92424765e-01,
        -9.28340784e-01, -9.21797691e-01, -7.33077941e-01,
        -8.73855389e-01],
       [ 1.14112826e+00,  7.36788398e-01,  8.49422738e-01,
         1.63395471e-01,  4.21502373e-02, -4.32218911e-01,
         9.70352254e-01, -1.01988514e+00, -6.92424765e-01,
         1.46696854e+00,  6.58426922e-01,  3.22554294e-01,
         1.17780509e+00],
       [-3.01594906e-01,  7.36788398e-01, -1.29648734e+00,
        -2.20825294e-01, -8.79581399e-01,  2.31364240e+00,
        -1.03535193e+00,  1.49097786e+00, -6.92424765e-01,
        -9.28340784e-01, -9.21797691e-01, -7.33077941e-01,
        -8.73855389e-01],
       [-1.63333936e+00,  7.36788398e-01,  8.49422738e-01,
        -1.20882154e+00, -1.59439369e+00, -4.32218911e-01,
         9.70352254e-01, -1.59253810e+00,  1.44420022e+00,
         7.82594450e-01,  6.58426922e

In [102]:
from sklearn.ensemble import RandomForestClassifier

clfr=RandomForestClassifier(n_estimators=10,criterion='entropy',random_state=0)

clfr.fit(x_train,y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

In [103]:
clfr1=RandomForestClassifier(n_estimators=10,criterion='gini',random_state=0)

clfr1.fit(x_train,y_train)

RandomForestClassifier(n_estimators=10, random_state=0)

In [104]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score

ypre=clfr1.predict(x_test)# entropy ypre calculation

ypre1=clfr1.predict(x_test)# gini ypre calculation


In [105]:
print('entropy Accuracy Score:')
accuracy_score(y_test,ypre)*100

entropy Accuracy Score:


79.62962962962963

In [106]:
print('gini Accuracy Score:')
accuracy_score(y_test,ypre1)*100

gini Accuracy Score:


79.62962962962963

As per the dataset Navie Baye's Algorithm fits the given dataset model Gaussian model 


So I prefer my client to go for Gaussian Naive Bayes Algorithm